repos
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy *.py #TODO: This will probably not work if we have more dirs
      language: python
      language_version: python3.11
      additional_dependencies: ["mypy"]
      types: [python]
      require_serial: true
      verbose: true
