repos:
 - repo: local
   hooks:
   - id: mypy
     name: mypy
     entry: mypy models/
     language: python
     language_version: python3.10
     types: [python]
     require_serial: true
     verbose: true
     always_run: true
     pass_filenames: false
